# Docs default config
github:
  repo: https://github.com/cecilapp/statidocs
  branch: main
manifest:
  background_color: '#EEF6FF'
  theme_color: '#1C4ED8'
serviceworker:
  enabled: false
docsearch:
  enabled: false
  version: '3'
highlightjs:
  version: '11.7.0'
jquery:
  version: '3.7.0'
tocbot:
  version: '4.18.2'

# Cecil config for Docs
pagination:
  enabled: false
pages:
  sortby: weight
  body:
    highlight:
      enabled: true
    images:
      class: "dark:brightness-90"
      resize:
        enabled: true
      webp:
        enabled: true
      responsive:
        enabled: true
      caption:
        enabled: true
    links:
      embed:
        enabled: true
